name: duvaai
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  http: ^1.2.1
  google_fonts: ^6.2.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  google_my_business: ^0.3.4
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  responsive_sizer: ^3.3.1
  uicons: ^1.0.1
  ionicons: ^0.2.2
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - lib/core/localization/en.json
    - lib/core/localization/es.json
    - assets/images/duva_ai_edited.svg
    - assets/images/profile.png

icons_launcher:
  image_path: "assets/images/duva_ai.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
