// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDB_fm0s3S1QQdhPyVpPePh3C6-WlmW04',
    appId: '1:344087960556:web:72d99a7ff08d7da7a9bec9',
    messagingSenderId: '344087960556',
    projectId: 'duvaai',
    authDomain: 'duvaai.firebaseapp.com',
    storageBucket: 'duvaai.appspot.com',
    measurementId: 'G-LPGX3T3XZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_gHZlvoHVtNzhlpBbTJOlnR6Z9d8vpc',
    appId: '1:344087960556:android:983019eaf1da6a2ba9bec9',
    messagingSenderId: '344087960556',
    projectId: 'duvaai',
    storageBucket: 'duvaai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbVro2ymrOGzCTQ2b_SjWWYd3SleBZI8E',
    appId: '1:344087960556:ios:ba3846b0dd09bf36a9bec9',
    messagingSenderId: '344087960556',
    projectId: 'duvaai',
    storageBucket: 'duvaai.appspot.com',
    androidClientId: '344087960556-5hhsfe9knd8bdlthrvkmsohhbkqctru6.apps.googleusercontent.com',
    iosClientId: '344087960556-al42rvb543fudaqru205nq897f8g4hml.apps.googleusercontent.com',
    iosBundleId: 'com.example.duvaai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbVro2ymrOGzCTQ2b_SjWWYd3SleBZI8E',
    appId: '1:344087960556:ios:ba3846b0dd09bf36a9bec9',
    messagingSenderId: '344087960556',
    projectId: 'duvaai',
    storageBucket: 'duvaai.appspot.com',
    androidClientId: '344087960556-5hhsfe9knd8bdlthrvkmsohhbkqctru6.apps.googleusercontent.com',
    iosClientId: '344087960556-al42rvb543fudaqru205nq897f8g4hml.apps.googleusercontent.com',
    iosBundleId: 'com.example.duvaai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDB_fm0s3S1QQdhPyVpPePh3C6-WlmW04',
    appId: '1:344087960556:web:d279677232318b14a9bec9',
    messagingSenderId: '344087960556',
    projectId: 'duvaai',
    authDomain: 'duvaai.firebaseapp.com',
    storageBucket: 'duvaai.appspot.com',
    measurementId: 'G-13B1CGKTEN',
  );

}